---
- name: Deploy node_exporter
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz

- name: unarchive node_exporter
  ansible.builtin.unarchive:
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    owner: root
    group: root
    mode: '0755'

- name: Generate UNIT
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'
  notify: restart node_exporter

- name: Enable Systemd
  ansible.builtin.systemd_service:
    name: node_exporter
    state: started
    daemon_reload: true
    enabled: true
