services:
  calibreweb:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "${CW_BIND_ADDRESS}:${CW_PORT}:8083"
    volumes:
      - ${CW_CONFIG}:/config:rw
      - ${CW_BOOKS}:/books:ro
    restart: unless-stopped
