services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: host
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=${PROM_RETENTION}
      - --web.enable-lifecycle
      - --web.listen-address=${PROM_BIND_ADDRESS}:${PROM_PORT}

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules:/etc/prometheus/rules:ro
      - ${PROM_DATA}:/prometheus
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    env_file:
      - ${GF_ENV_FILE}
    ports:
      - "${GF_BIND_ADDRESS}:${GF_PORT}:3000"
    volumes:
      - ${GF_DATA}:/var/lib/grafana
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    network_mode: host
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--web.listen-address=${NE_BIND_ADDRESS}:${NE_PORT}'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
