name: Ansible-lint

on:
  push:
  pull_request:
    branches: [main]

jobs:
  Ansible_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v6
      - run: pip install ansible-lint
      - run: ansible-lint ansible/
